[project]
name = "micropython-uncrustify"
version = "1.0.0"

[build-system]
requires = [
  "setuptools>=42",
  "scikit-build",
  "cmake",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"
